name: torch-audiomentations-gpu
channels:
- defaults
- pytorch
dependencies:
- cudatoolkit=10.1
- ffmpeg
- matplotlib>=3,<4
- numpy>=1.15,<1.18
- pip>=20.1,<=21
- python=3.7.3
- pytorch::pytorch=1.7.1
- scipy=1.5.2
- seaborn>=0.9,<0.11
- pytorch::torchaudio>=0.7.0,<0.9
- pip:
  - audiomentations==0.12.1
  - audioread==2.1.8
  - black
  - coverage==5.3
  - ffmpeg-python
  - julius>=0.2.3,<0.3
  - librosa>=0.6.1,<=0.8
  - pandas==1.1.4
  - py-cpuinfo==7.0.0
  - pytest==5.3.4
  - pytest-cov==2.8.1
  - PyYAML==5.3.1
  - setuptools>=41.0.0
  - tqdm==4.49.0
  - twine
  - torch-pitch-shift>=1.2.0